name: gainpath_workspace
description: GainPath applications and shared package workspace.
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.6.0 <4.0.0'

workspace:
  - apps/mobile
  - apps/admin_web
  - packages/gainpath_domain
  - packages/gainpath_data
  - packages/gainpath_ui
  - packages/gainpath_pose
  - packages/gainpath_identity

dev_dependencies:
  analyzer: ^8.4.1
  yaml: ^3.1.3
  path: ^1.9.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  bloc_test: ^10.0.0
  test: ^1.25.0
